# Generated by Django 2.1.7 on 2019-02-13 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nasdaqstat', '0002_auto_20190212_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('relation', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='InsiderTrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_date', models.DateField()),
                ('transaction_type', models.CharField(max_length=60)),
                ('owner_type', models.CharField(max_length=40)),
                ('shares_traded', models.FloatField()),
                ('last_price', models.FloatField(blank=True, null=True)),
                ('shares_held', models.FloatField()),
                ('insider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nasdaqstat.Insider')),
                ('ticker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nasdaqstat.Company')),
            ],
        ),
    ]
